### ISSUE TITLE
Warning when solve is executed

### ISSUE THREAD

**Issue by ktitimbo** [SciML/ODEInterfaceDiffEq.jl#49]
When solving the minimal example in README I now get the following warning

`┌ Warning: Backwards compatability support of the new return codes to Symbols will be deprecated with the Julia v1.9 release. Please see https://docs.sciml.ai/SciMLBase/stable/interfaces/Solutions/#retcodes for more information`

Also links in README are broken

**Comment by ChrisRackauckas** [comment]
Thanks, I fixed the README links and the enums fix is https://github.com/SciML/ODEInterfaceDiffEq.jl/pull/50 which will be tagged and merged in about an hour.
